### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Salmondx** [billziss-gh/winfuse#3]
Hi! Sorry if it's a weird question but I'm not fully understand what's the idea of this project and how to install it. I saw your comments on a WSL1 thread and decided to check tools that you've built (great work btw!).

I've never worked or used FUSE before and correct me if I'm wrong, but as I understand this project will allow me to mount external file systems that will be visible both to windows and WSL1? WSL1 have a terrible file system performance and as I understand this tool is supposed to fix it by mounting a different drive with different FS?

Thanks!

**Comment by billziss-gh** [comment]
This project provides a way for unmodified (or almost unmodified) Linux FUSE file systems to run on WSL1 and expose a drive to both WSL1 and Windows. It does not attempt to address file system performance issues of WSL1.

This project may be useful to 2 audiences:

- Linux FUSE file system developers that may wish to easily run their file systems on WSL1 and Windows, without having to "port" them first.

- WSL1 users that wish to run any FUSE file system on Windows.

Hope this make sense.

**Comment by Salmondx** [comment]
Thanks for explanation!
