### ISSUE TITLE
fusermount: mount failed: No such device

### ISSUE THREAD

**Issue by BytesAndCoffee** [billziss-gh/winfuse#4]
Installed all prerequisites, rebooted Windows, launched wsl1 (Ubuntu 18.04.4 LTS on Windows 10 20H1 build 19041.572), ran `sudo sh '/mnt/c/Program Files/WinFuse/opt/wslfuse/install.sh'`, no errors. 

/dev/fuse confirmed to be created. 

Ran ` sshfs -d -o umask=000 USER@HOST: mnt`, replacing USER and HOST with applicable values, sshfs returns error in issue title

**Comment by billziss-gh** [comment]
This error is returned by the libfuse `fusermount` program in [`do_mount`](https://github.com/libfuse/libfuse/blob/master/util/fusermount.c#L898). This means that the libfuse `fusermount` program was not replaced by the winfuse version (which knows how to mount file systems in WSL1).

Can you please try the following commands for me:

- `ls -l /dev/fuse`
- `ls -l /usr/bin/fusermount*`

Here is output from my local system:

```
billziss@xps:~$ sudo sh "/mnt/c/Program Files/WinFuse/opt/wslfuse/install.sh"
[sudo] password for billziss:
FUSE for WSL1 user space components installed
billziss@xps:~$ ls -l /dev/fuse
crw-rw-rw- 1 root root 10, 229 Oct 23 13:17 /dev/fuse
billziss@xps:~$ ls -l /usr/bin/fusermount*
-rwsr-xr-x 1 root root 34040 Aug 22 22:33 /usr/bin/fusermount
-rwxr-xr-x 1 root root  5632 Aug 22 22:33 /usr/bin/fusermount-helper.exe
-rwsr-xr-x 1 root root 39144 Mar  7  2020 /usr/bin/fusermount.~1~
-rwsr-xr-x 1 root root 33984 Aug 12 09:39 /usr/bin/fusermount.~2~
-rwsr-xr-x 1 root root 34040 Aug 22 22:33 /usr/bin/fusermount3
-rwsr-xr-x 1 root root 33984 Aug 12 09:39 /usr/bin/fusermount3.~1~
```

(The `fusermount*.~*~` files can be ignored as they are backups of the original libfuse `fusermount` and `fusermount3` programs.)

**Comment by BytesAndCoffee** [comment]
Here's the output:

```
[04:35:58]:~> michael@Rocket$ sudo sh "/mnt/c/Program Files/WinFuse/opt/wslfuse/install.sh"
FUSE for WSL1 user space components installed
[04:36:15]:~> michael@Rocket$ ls -l /dev/fuse
crw-rw-rw- 1 root root 10, 229 Oct 23 11:05 /dev/fuse
[04:36:37]:~> michael@Rocket$ ls -l /usr/bin/fusermount*
-rwsr-xr-x 1 root root 34040 Oct 23 10:58 /usr/bin/fusermount
-rwsr-xr-x 1 root root 34040 Oct 23 10:58 /usr/bin/fusermount3
-rwxr-xr-x 1 root root  5632 Oct 23 10:58 /usr/bin/fusermount-helper.exe

**Comment by billziss-gh** [comment]
It appears that you have the correct versions of `fusermount` and `fusermount3` installed (they are both 34040 bytes as in my system and you also have the `fusermount-helper.exe` Windows program).

However the "fusermount: mount failed" message is never output by the `fusermount` that ships with WinFuse. This suggests that libfuse executes its own `fusermount` program, which is the "wrong" one for WSL1.

Given that `fusermount` is usually installed in `/usr/bin` I am uncertain how this would be possible. Do you have an unusual installation of FUSE on your machine?

Please also note that my tests have been against Ubuntu 20.04. As far as I can remember Ubuntu 18.04 did not include FUSE3 in its packages, which means that it does not have the latest version of SSHFS against which my tests were done.

**Comment by ZhangTianrong** [comment]
> Here's the output:
> 
> ```
> [04:35:58]:~> michael@Rocket$ sudo sh "/mnt/c/Program Files/WinFuse/opt/wslfuse/install.sh"
> FUSE for WSL1 user space components installed
> [04:36:15]:~> michael@Rocket$ ls -l /dev/fuse
> crw-rw-rw- 1 root root 10, 229 Oct 23 11:05 /dev/fuse
> [04:36:37]:~> michael@Rocket$ ls -l /usr/bin/fusermount*
> -rwsr-xr-x 1 root root 34040 Oct 23 10:58 /usr/bin/fusermount
> -rwsr-xr-x 1 root root 34040 Oct 23 10:58 /usr/bin/fusermount3
> -rwxr-xr-x 1 root root  5632 Oct 23 10:58 /usr/bin/fusermount-helper.exe
> ```

Hi, I got the same output as yours. Can you please share how you fix the problem. I am using Ubuntu 20.04. In my case the error message from `sshfs` is `fuse: device not found, try 'modprobe fuse' first` though. Similar error when using `davfs`, which says it cannot open fuse device when `/dev/fuse` is already created.

**Comment by RYNO8** [comment]
Hi I had the same problem too. I ran sshfs without sudo and it worked.
